// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ViewPasswordJS() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n        document.addEventListener('DOMContentLoaded', function() {\n            const togglePasswordButtons = document.querySelectorAll('.toggle-password-visibility');\n\n            togglePasswordButtons.forEach(button => {\n                const targetInputId = button.dataset.targetInput; // Get the target input's ID from the data attribute\n\n                if (!targetInputId) {\n                    console.warn('Button is missing data-target-input attribute:', button);\n                    return;\n                }\n\n                const passwordInput = document.getElementById(targetInputId);\n\n                const eyeIcon = button.querySelector('.eye-icon');\n                const eyeSlashIcon = button.querySelector('.eye-slash-icon');\n\n                if (passwordInput && eyeIcon && eyeSlashIcon) {\n                    button.addEventListener('click', function () {\n                        const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';\n                        passwordInput.setAttribute('type', type);\n\n                        if (type === 'text') {\n                            eyeIcon.classList.add('hidden');\n                            eyeSlashIcon.classList.remove('hidden');\n                        } else {\n                            eyeIcon.classList.remove('hidden');\n                            eyeSlashIcon.classList.add('hidden');\n                        }\n                    });\n                } else {\n                    if (!passwordInput) console.warn('Could not find password input with ID:', targetInputId, 'for button:', button);\n                    if (!eyeIcon) console.warn('Could not find .eye-icon in button:', button);\n                    if (!eyeSlashIcon) console.warn('Could not find .eye-slash-icon in button:', button);\n                }\n            });\n        });\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
